"""Abstract broker interface and the order/position value objects.

Every adapter (MT5, FIX, simulated) implements :class:`BrokerBase`, so the
:class:`~quant_system.execution.brokers.router.OrderRouter` never needs to know
which venue it is talking to.
"""

from __future__ import annotations

import time
import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import AsyncIterator, Dict, List, Mapping, Optional

import pandas as pd


class BrokerError(RuntimeError):
    """Base class for every broker-related failure."""


class BrokerNotConnectedError(BrokerError):
    """Raised when an operation is attempted before :meth:`BrokerBase.connect`."""


class OrderRejectedError(BrokerError):
    """Raised when the venue refuses an order."""


class OrderSide(str, Enum):
    """Order direction."""

    BUY = "buy"
    SELL = "sell"


class OrderType(str, Enum):
    """Order type."""

    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"


class OrderStatus(str, Enum):
    """Lifecycle state of an order."""

    PENDING = "pending"
    ACCEPTED = "accepted"
    PARTIALLY_FILLED = "partially_filled"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"


@dataclass
class Order:
    """A broker-agnostic order request.

    Attributes:
        symbol: Instrument symbol.
        side: Buy or sell.
        quantity: Absolute number of units (fractional supported where the venue
            allows it).
        order_type: Market / limit / stop.
        price: Limit or stop price (required for non-market orders).
        client_order_id: Unique id generated by the client; used for idempotency
            and for cancellation.
        strategy: Originating strategy name.
        tag: Free-form reason code.
        time_in_force: FIX time-in-force code (``"1"`` GTC, ``"3"`` IOC).
        metadata: Adapter-specific extras (magic number, filling mode, ...).
    """

    symbol: str
    side: OrderSide
    quantity: float
    order_type: OrderType = OrderType.MARKET
    price: Optional[float] = None
    client_order_id: str = field(default_factory=lambda: uuid.uuid4().hex[:16])
    strategy: str = ""
    tag: str = ""
    time_in_force: str = "3"  # IOC by default for systematic execution
    metadata: Dict[str, object] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate the order.

        Raises:
            ValueError: If quantity is not positive or a limit/stop order has no price.
        """
        if self.quantity <= 0:
            raise ValueError(f"Order quantity must be positive; got {self.quantity}.")
        if self.order_type in (OrderType.LIMIT, OrderType.STOP) and self.price is None:
            raise ValueError(f"{self.order_type.value} orders require a price.")
        if isinstance(self.side, str):
            self.side = OrderSide(self.side)
        if isinstance(self.order_type, str):
            self.order_type = OrderType(self.order_type)

    @property
    def signed_quantity(self) -> float:
        """Quantity signed by direction (positive = buy)."""
        return self.quantity if self.side == OrderSide.BUY else -self.quantity


@dataclass
class OrderReport:
    """Venue acknowledgement for an order.

    Attributes:
        client_order_id: Matching :attr:`Order.client_order_id`.
        broker_order_id: Venue-assigned id (``None`` until acknowledged).
        status: Current lifecycle state.
        filled_quantity: Units filled so far.
        average_fill_price: Volume-weighted average fill price.
        message: Human-readable venue message or error text.
        timestamp: Acknowledgement time (epoch seconds).
        raw: Raw venue payload for auditing.
    """

    client_order_id: str
    broker_order_id: Optional[str] = None
    status: OrderStatus = OrderStatus.PENDING
    filled_quantity: float = 0.0
    average_fill_price: float = 0.0
    message: str = ""
    timestamp: float = field(default_factory=time.time)
    raw: Optional[Mapping[str, object]] = None


@dataclass
class PositionReport:
    """A position held at the venue.

    Attributes:
        symbol: Instrument symbol.
        quantity: Signed units (negative = short).
        average_price: Average entry price.
        last_price: Latest venue mark.
        unrealized_pnl: Venue-reported unrealised PnL.
        strategy: Strategy attribution, when the venue supports it.
    """

    symbol: str
    quantity: float
    average_price: float
    last_price: float
    unrealized_pnl: float = 0.0
    strategy: str = ""


@dataclass
class BrokerAccount:
    """Account-level snapshot.

    Attributes:
        equity: Account equity.
        cash: Free cash / balance.
        margin_used: Margin currently consumed.
        margin_available: Free margin.
        currency: Account currency.
        raw: Raw venue payload.
    """

    equity: float
    cash: float
    margin_used: float = 0.0
    margin_available: float = 0.0
    currency: str = "USD"
    raw: Optional[Mapping[str, object]] = None


class BrokerBase(ABC):
    """Abstract base class implemented by every broker adapter.

    Implementations must be safe to use as an async context manager and must
    never raise for routine rejections - those surface as
    :class:`OrderReport` with ``status=REJECTED``.
    """

    #: Human-readable adapter name.
    name: str = "abstract"

    def __init__(self, config: Optional[object] = None) -> None:
        """Initialise the adapter.

        Args:
            config: Broker configuration object (typically
                :class:`~quant_system.config.settings.BrokerConfig`).
        """
        self.config = config
        self._connected: bool = False

    # ------------------------------------------------------------------ #
    # Connection lifecycle
    # ------------------------------------------------------------------ #
    @abstractmethod
    def connect(self) -> None:
        """Establish the session with the venue."""

    @abstractmethod
    def disconnect(self) -> None:
        """Tear the session down cleanly."""

    @property
    def is_connected(self) -> bool:
        """Whether the session is live."""
        return self._connected

    def _require_connection(self) -> None:
        """Raise if the adapter is not connected.

        Raises:
            BrokerNotConnectedError: If :attr:`is_connected` is ``False``.
        """
        if not self._connected:
            raise BrokerNotConnectedError(f"{self.name} is not connected.")

    # ------------------------------------------------------------------ #
    # Trading
    # ------------------------------------------------------------------ #
    @abstractmethod
    def submit_order(self, order: Order) -> OrderReport:
        """Send an order to the venue.

        Args:
            order: The order to send.

        Returns:
            An :class:`OrderReport` describing the immediate outcome.
        """

    @abstractmethod
    def cancel_order(self, client_order_id: str) -> OrderReport:
        """Cancel a working order.

        Args:
            client_order_id: The client id of the order to cancel.

        Returns:
            The resulting :class:`OrderReport`.
        """

    @abstractmethod
    def get_positions(self) -> List[PositionReport]:
        """Fetch all open positions at the venue."""

    @abstractmethod
    def get_account(self) -> BrokerAccount:
        """Fetch the account snapshot."""

    # ------------------------------------------------------------------ #
    # Market data (optional)
    # ------------------------------------------------------------------ #
    async def stream_quotes(self, symbols: List[str]) -> AsyncIterator[Dict[str, float]]:
        """Yield live quotes for ``symbols``.

        The default implementation raises :class:`NotImplementedError`;
        adapters that support streaming override it.

        Args:
            symbols: Symbols to subscribe to.

        Yields:
            Dictionaries of ``{"symbol", "bid", "ask", "last", "timestamp"}``.

        Raises:
            NotImplementedError: When the adapter cannot stream quotes.
        """
        raise NotImplementedError(f"{self.name} does not support quote streaming.")
        yield {}  # pragma: no cover - keeps the generator signature valid

    def get_bars(
        self,
        symbol: str,
        timeframe: str = "1d",
        count: int = 500,
    ) -> pd.DataFrame:
        """Fetch recent bars from the venue.

        Args:
            symbol: Instrument symbol.
            timeframe: Bar interval.
            count: Number of bars.

        Returns:
            OHLCV DataFrame (empty when unsupported).
        """
        return pd.DataFrame()

    # ------------------------------------------------------------------ #
    # Context manager
    # ------------------------------------------------------------------ #
    def __enter__(self) -> "BrokerBase":
        """Connect on entry."""
        self.connect()
        return self

    def __exit__(self, exc_type: object, exc: object, tb: object) -> None:
        """Disconnect on exit."""
        self.disconnect()


__all__: List[str] = [
    "BrokerError",
    "BrokerNotConnectedError",
    "OrderRejectedError",
    "OrderSide",
    "OrderType",
    "OrderStatus",
    "Order",
    "OrderReport",
    "PositionReport",
    "BrokerAccount",
    "BrokerBase",
]
